shutdown: false

controller_frequency: 10.0
controller_patience: 3.0
recovery_behavior_enabled: false # 复原行为使能
clearing_rotation_allowed: false # 清除旋转允许

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2



base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_global_palnner: "navfn/NavfnROS"
#alternatives: global_planner/GlobalPlanner,carrot_planner/CarrotPlanner